import type { Metadata } from "next";
import { Inter, Ultra } from "next/font/google";
import "../styles/globals.css";

const inter = Inter({ 
  subsets: ["latin"], 
  variable: '--font-inter', 
});

const ultra = Ultra({
  subsets: ["latin"],
  variable: '--font-ultra',
  weight: "400",
  display: "swap"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body className={`${inter.variable} ${ultra.variable}`}>{children}</body>
    </html>
  );
}
